LABEL_KEY = 'Label'
TYPE_KEY = 'Type'
TYPE_GAS = 'gas-phase'
TYPE_SOL = 'solvated'
STATUS_KEY = 'Status'
STATUS_READY = 'Ready'
STATUS_COMPLETE = 'Complete'
STATUS_JOBID_PREFIX = 'JID-'
STATUS_FAILED = 'Failed'
STATUS_ERROR = 'Error'
DATE_KEY = 'Date'
IONS_KEY = 'Ions'
IONS_YES = 'Yes'
IONS_NO = 'No'
ENERGY_KEY = 'Energy'
ROTAMER_LIST_KEY = 'RotamerList'

