site_name: GEMS
site_description:  Documentation for the GLYCAM Extensible Modeling Scripts
nav: 
  - 'Overview': 'index.md'
  - 'Building': 'building.md'
  - 'GEMS Modules': 
    - 'About' : 'gemsModules/about.md'
    - 'Workflow' : 'gemsModules/workflow.md'
    - 'The Modules' : 
      - 'List of Modules' : 'gemsModules/the_modules.md'
      - 'Sequence' :
        - 'Overview' : 'gemsModules/sequence/overview.md'
        - 'Workflow' : 'gemsModules/sequence/Overview/New_Sequence_Target_Workflow.dot'
        - 'Services': 'gemsModules/sequence/services.md'
  - 'Notable Services' : 'gemsModules/notable_services.md'
  - 'Examples': 'examples.md'
  - 'Testing' : 'testing.md'

