# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gems_grpc_slurm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15gems_grpc_slurm.proto\x12\rGemsGrpcSlurm"%\n\x14GemsGrpcSlurmRequest\x12\r\n\x05input\x18\x01 \x01(\t"\'\n\x15GemsGrpcSlurmResponse\x12\x0e\n\x06output\x18\x01 \x01(\t2u\n\rGemsGrpcSlurm\x12\x64\n\x15GemsGrpcSlurmReceiver\x12#.GemsGrpcSlurm.GemsGrpcSlurmRequest\x1a$.GemsGrpcSlurm.GemsGrpcSlurmResponse"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "gems_grpc_slurm_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _GEMSGRPCSLURMREQUEST._serialized_start = 40
    _GEMSGRPCSLURMREQUEST._serialized_end = 77
    _GEMSGRPCSLURMRESPONSE._serialized_start = 79
    _GEMSGRPCSLURMRESPONSE._serialized_end = 118
    _GEMSGRPCSLURM._serialized_start = 120
    _GEMSGRPCSLURM._serialized_end = 237
# @@protoc_insertion_point(module_scope)
