# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gems_grpc_slurm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gems_grpc_slurm.proto',
  package='GemsGrpcSlurm',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15gems_grpc_slurm.proto\x12\rGemsGrpcSlurm\"%\n\x14GemsGrpcSlurmRequest\x12\r\n\x05input\x18\x01 \x01(\t\"\'\n\x15GemsGrpcSlurmResponse\x12\x0e\n\x06output\x18\x01 \x01(\t2u\n\rGemsGrpcSlurm\x12\x64\n\x15GemsGrpcSlurmReceiver\x12#.GemsGrpcSlurm.GemsGrpcSlurmRequest\x1a$.GemsGrpcSlurm.GemsGrpcSlurmResponse\"\x00\x62\x06proto3')
)




_GEMSGRPCSLURMREQUEST = _descriptor.Descriptor(
  name='GemsGrpcSlurmRequest',
  full_name='GemsGrpcSlurm.GemsGrpcSlurmRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='GemsGrpcSlurm.GemsGrpcSlurmRequest.input', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=77,
)


_GEMSGRPCSLURMRESPONSE = _descriptor.Descriptor(
  name='GemsGrpcSlurmResponse',
  full_name='GemsGrpcSlurm.GemsGrpcSlurmResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='GemsGrpcSlurm.GemsGrpcSlurmResponse.output', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['GemsGrpcSlurmRequest'] = _GEMSGRPCSLURMREQUEST
DESCRIPTOR.message_types_by_name['GemsGrpcSlurmResponse'] = _GEMSGRPCSLURMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GemsGrpcSlurmRequest = _reflection.GeneratedProtocolMessageType('GemsGrpcSlurmRequest', (_message.Message,), {
  'DESCRIPTOR' : _GEMSGRPCSLURMREQUEST,
  '__module__' : 'gems_grpc_slurm_pb2'
  # @@protoc_insertion_point(class_scope:GemsGrpcSlurm.GemsGrpcSlurmRequest)
  })
_sym_db.RegisterMessage(GemsGrpcSlurmRequest)

GemsGrpcSlurmResponse = _reflection.GeneratedProtocolMessageType('GemsGrpcSlurmResponse', (_message.Message,), {
  'DESCRIPTOR' : _GEMSGRPCSLURMRESPONSE,
  '__module__' : 'gems_grpc_slurm_pb2'
  # @@protoc_insertion_point(class_scope:GemsGrpcSlurm.GemsGrpcSlurmResponse)
  })
_sym_db.RegisterMessage(GemsGrpcSlurmResponse)



_GEMSGRPCSLURM = _descriptor.ServiceDescriptor(
  name='GemsGrpcSlurm',
  full_name='GemsGrpcSlurm.GemsGrpcSlurm',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=120,
  serialized_end=237,
  methods=[
  _descriptor.MethodDescriptor(
    name='GemsGrpcSlurmReceiver',
    full_name='GemsGrpcSlurm.GemsGrpcSlurm.GemsGrpcSlurmReceiver',
    index=0,
    containing_service=None,
    input_type=_GEMSGRPCSLURMREQUEST,
    output_type=_GEMSGRPCSLURMRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GEMSGRPCSLURM)

DESCRIPTOR.services_by_name['GemsGrpcSlurm'] = _GEMSGRPCSLURM

# @@protoc_insertion_point(module_scope)
