# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: json.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\njson.proto\x12\x04json\"\x1c\n\x0bJSONRequest\x12\r\n\x05input\x18\x01 \x01(\t\"\x1e\n\x0cJSONResponse\x12\x0e\n\x06output\x18\x01 \x01(\t2A\n\x04JSON\x12\x39\n\x0eJSON_Delegator\x12\x11.json.JSONRequest\x1a\x12.json.JSONResponse\"\x00\x42$\n\x13glycamweb.grpc.jsonB\x04JSONP\x01\xa2\x02\x04JSONb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'json_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023glycamweb.grpc.jsonB\004JSONP\001\242\002\004JSON'
  _JSONREQUEST._serialized_start=20
  _JSONREQUEST._serialized_end=48
  _JSONRESPONSE._serialized_start=50
  _JSONRESPONSE._serialized_end=80
  _JSON._serialized_start=82
  _JSON._serialized_end=147
# @@protoc_insertion_point(module_scope)
