# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import json_pb2 as json__pb2


class JSONStub(object):
    """The JSON service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JSON_Delegator = channel.unary_unary(
                '/json.JSON/JSON_Delegator',
                request_serializer=json__pb2.JSONRequest.SerializeToString,
                response_deserializer=json__pb2.JSONResponse.FromString,
                )


class JSONServicer(object):
    """The JSON service definition.
    """

    def JSON_Delegator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JSONServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JSON_Delegator': grpc.unary_unary_rpc_method_handler(
                    servicer.JSON_Delegator,
                    request_deserializer=json__pb2.JSONRequest.FromString,
                    response_serializer=json__pb2.JSONResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'json.JSON', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class JSON(object):
    """The JSON service definition.
    """

    @staticmethod
    def JSON_Delegator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/json.JSON/JSON_Delegator',
            json__pb2.JSONRequest.SerializeToString,
            json__pb2.JSONResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
