#!/bin/bash

if [ `git rev-parse --abbrev-ref HEAD` == "master" ]; then
	echo "
             No hooks are used on this branch        
	Do "git checkout gems-dev" to switch branches
"   

else
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
for h_file in $BASEDIR/pre-commit.d/pre-commit.*
do
	if [ -f "$h_file" ]
	then
		source $h_file "$@"
		h_file_return=$?
		if [ $h_file_return == 0 ]
		then
			echo "$h_file --- SUCCESSFUL"
		else
			echo "$h_file --- FAILED"
			exit $h_file_return
		fi
	fi
done
fi
