#!/usr/bin/env python3
from gemsModules.logging.logger import Set_Up_Logging
log = Set_Up_Logging(__name__)

##  Purpose: generate the file to be given as an argument to sbatch
##  
##  Input: 
##          - Working directory
##          - Execution and processing requests (can be overridden for security)
##            - Computing parameters, including:
##              - processing
##                - CPU or GPU preferences
##                - number of CPUs / GPUs
##                - number of nodes
##                - Optional parameters (typical to slurm, but we don't often use bc don't use tasks)
##                  - tasks per node (optional)
##                  - cpus per task (optional)
##                - processors per node (= cores, typically)
##                  - NOTE: the actual number of processes run per node should be managed by the message passing
##                  -       this is not a normal Slurm requirement - for now, it is a requirement here
##                  - NOTE: Make the instance config return info about whether 'procs' is cores or threads.
##                - 
##                - 
##                - 
##              - job name
##              - parition (queue) to use
##              - user name for submission
##              - get-user-env
##              - time limit
##              - output & error file prefixes (names)
##              - 
##              - 
##            - Environmental options 
##              - pUUID (for provenance and tracking)
##              - testing workflow
##              - debugging level
##              - context (website, localhost, etc.)
##              - 
##          - Path+name of the file to be generated by this script
##          - Details of script to be executed by the file generated here
##            - Path+name of script
##            - Arguments to the script (optional)
##  Output:
##          - Path to the sbatch argument file
##  
##  
##  




## Locations of code that was merged / modified
##
# complex/amber_receive.py:from gemsModules.batchcompute.slurm.receive import receive as slurm_receive
# complex/antibody/tasks/create_slurm_submission.py  <<< this file is probably unused; consider for deletion
# complex/glycomimetics/tasks/create_slurm_submission.py <<< this is probably used; delete if possible
#                                                            don't take lots of time with this if not necessary

## All the local imports from the files above
from gemsModules.batchcompute.slurm.receive import receive as slurm_receive
AAAA from gemsModules.deprecated.instance_config.main import InstanceConfig
from gemsModules.mmservice.mdaas_amber import mdaas_io
from gemsModules.systemoperations.environment_ops import is_GEMS_test_workflow
from gemsModules.systemoperations import filesystem_ops

