#!/usr/bin/env python3
import os 

from gemsModules.networkconnections.seek_correct_host import execute as seek_correct_host
from gemsModules.systemoperations.environment_ops import get_site_version

from gemsModules.configuration.main_api import session_instance_config as theIC

from gemsModules.complex.antibody.json_string_manager import (
    Antibody_Json_String_Manager,
)
from gemsModules.complex.antibody.main_settings import WhoIAm, context_names
from gemsModules.logging.logger import Set_Up_Logging



log = Set_Up_Logging(__name__)


def receive(incomingString: str) -> str:
    log.info("Antibody was called as an entity.  Processing.")
    if not theIC.localhost_supports_context(context_names=["AD", "AntibodyDocking"]) :
        log.info("This is not the correct host to submit to.")
        log.info("Seeking correct host.")
        response = seek_correct_host(incomingString, WhoIAm, submission_fn_type="json")
        return response
    else:
        log.info("This is the correct host to submit to.")
    
    Antibody_manager = Antibody_Json_String_Manager()
    Antibody_manager_error_response = Antibody_manager.process(
        incoming_string=incomingString
    )

    if Antibody_manager_error_response is not None:
        log.debug("The incoming string is not valid")
        return Antibody_manager_error_response

    log.debug("The incoming string is valid")
    
    # Write the response to a a file in the project directory
    # TODO/fixme: If this is a build request, it will use the autogenerated Build pUUID instead of the pUUID given to build.
    output_path = Antibody_manager.transaction.outputs.project.project_dir
    if os.path.exists(output_path) is False:
        log.debug("The output path does not exist")
    else:
        response_json_path = output_path + "/response.json"
        with open(response_json_path, "w") as f:
            f.write(Antibody_manager.transaction.get_outgoing_string(prettyPrint=True))
            f.write("\n")
    
    # Return the response in a condensed format for the API
    return Antibody_manager.transaction.get_outgoing_string()
