@startuml StakeHolderBrief
!include <archimate/Archimate>
Motivation_Stakeholder(GEMSDevelopers, "GEMS\nDevelopers") 
Motivation_Stakeholder(SciStudent, "Natural Science\nStudents") 
Motivation_Stakeholder(CSStudent, "Computer Science\nStudents") 
Motivation_Constraint(LittleCS, "Little\nComputer Science")
Motivation_Constraint(LittleNatS, "Little\nNatural Science")
Motivation_Constraint(LittleTime, "Little\nTime")

Rel_Composition_Right(SciStudent, LittleCS)
Rel_Composition_Right(CSStudent, LittleNatS)
Rel_Composition_Right(GEMSDevelopers, LittleTime)

Grouping(Users, "Users"){
    Motivation_Stakeholder(Website, "Website")
    Motivation_Stakeholder(CLIUsers, "CLI\nUsers") 
    Motivation_Stakeholder(WebAPIUsers, "Web API\nUsers")
}

Grouping(ServicesLogic, "Services Logic"){
    Business_Product(GEMS_Code, "Other\nGEMS Code")
    Business_Product(GMML, "GMML")
    Business_Product(ExtApps, "External\nApplications")
}
Business_Interface(ServLogicInterface, "Arbitrary\nInterface")

Business_Interface(UserInterface, "JSON API with\nUser Friendly\nInterface")
Application_Component(gemsModules, "GEMS Modules")

Rel_Access_rw(Users, UserInterface)
Rel_Composition(gemsModules, UserInterface)
Rel_Composition(ServicesLogic, ServLogicInterface)
Rel_Access_rw(gemsModules, ServLogicInterface, "Read/Write")

Rel_Access_w(SciStudent, ServLogicInterface, "Write")
Rel_Access_w(SciStudent, ServicesLogic, "Write")

Rel_Access_w(GEMSDevelopers, gemsModules, "Write")
Rel_Access_w(CSStudent, gemsModules, "Write")

@enduml
